export const SHOW_FORM = "SHOW_FORM";

export const CLOSE_FORM = "CLOSE_FORM";

// Đẩy dữ liệu API vào Redux
export const FETCH_LIST_PRODUCT = "FETCH_LIST_PRODUCT";
export const FETCH_LIST_MANUFACTURER = "FETCH_LIST_MANUFACTURER";
export const FETCH_LIST_CATEGORY = "FETCH_LIST_CATEGORY";
//

// Update Product
export const PRODUCT_UPDATE = "PRODUCT_UPDATE";
export const SHOW_UPDATE_FORM = "SHOW_UPDATE_FORM";
export const CLOSE_UPDATE_FORM = "CLOSE_UPDATE_FORM";

export const DELETE_PRODUCT = "DELETE_PRODUCT";
